# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fe38af17172c8af2cd2d26bd265441849a0095c7452bf762b43e6cd3c1f319935ce6943357a27a16a1ee34bceb6ead91a4098b78598b2eeaba0887d3be51b71

test:
  secret_key_base: d77bdf5835c2d7ab827b18462c665631cc7ba6727f2298d9c420f038c1339deec6f2ede04df01ea75504534b46de2e69e0c298952cd031bb41390ddfa844836b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
